# Generated by Django 4.0.3 on 2022-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_profile_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mediakit',
            field=models.FileField(default=1, upload_to='../clients'),
            preserve_default=False,
        ),
    ]
