# Generated by Django 4.0.3 on 2022-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_profile_mediakit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mediakit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='site',
        ),
        migrations.AddField(
            model_name='profile',
            name='AdRiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
