# Generated by Django 4.0.3 on 2022-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_profile_mediakit_remove_profile_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mediakit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
