# Generated by Django 4.0.3 on 2022-08-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_profile_margins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TT_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='example_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mediakit_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
