# Generated by Django 4.0.3 on 2022-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_profile_tt_text_profile_example_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='margins',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seasons',
        ),
    ]
