# Generated by Django 3.2.4 on 2021-07-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0020_alter_client_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name_rk',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
