# Generated by Django 3.2.4 on 2021-07-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0023_brief_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='CRM',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='UTP',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='brief',
            name='audience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='companies_before',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='brief',
            name='competitors',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='geography',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='instrument',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='brief',
            name='landing_page',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='name_rk',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='official_list',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='suggestions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brief',
            name='sum_all',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='terms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='who_prep_materials',
            field=models.CharField(max_length=300),
        ),
    ]
