# Generated by Django 3.2.4 on 2021-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0026_remove_brief_sum_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='period',
        ),
        migrations.AddField(
            model_name='brief',
            name='period_c',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='period_p',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
