# Generated by Django 3.2.4 on 2021-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0029_auto_20210709_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='file',
            field=models.FileField(null=True, upload_to='client'),
        ),
    ]
