# Generated by Django 3.2.4 on 2021-07-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0034_auto_20210714_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brief',
            old_name='materils',
            new_name='materials',
        ),
    ]
