# Generated by Django 3.2.4 on 2021-07-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0043_alter_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='username',
        ),
    ]
