# Generated by Django 3.2.4 on 2021-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0056_alter_client_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief_pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Dmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pattern')),
                ('corrected', models.BooleanField(default=False)),
                ('file_content', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pattern')),
            ],
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
    ]
