# Generated by Django 3.2.4 on 2021-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0064_auto_20210721_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='budget',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
