# Generated by Django 3.2.4 on 2021-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0065_brief_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='AK',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='DCM',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='discount',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='img',
            field=models.FileField(default=1, upload_to='clients/img/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>'),
            preserve_default=False,
        ),
    ]
