# Generated by Django 3.2.4 on 2021-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0072_auto_20210726_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_file',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
