# Generated by Django 3.2.4 on 2021-07-27 06:09

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0074_alter_brief_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='calculation',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name, verbose_name='Изображение'),
        ),
    ]
