# Generated by Django 3.2.4 on 2021-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0083_auto_20210730_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleared',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
