# Generated by Django 3.2.4 on 2021-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0084_cleared_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='duration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='brief',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='brief',
            name='country',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='brief',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='brief',
            name='income',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='brief',
            name='materials',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='brief',
            name='period_c',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='brief',
            name='period_p',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='brief',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brief',
            name='type_act',
            field=models.CharField(max_length=60),
        ),
    ]
