# Generated by Django 3.2.2 on 2021-08-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0090_data_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name_rk',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exel.data'),
        ),
    ]
