# Generated by Django 3.2.2 on 2021-08-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0093_alter_materials_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='exel.materials'),
            preserve_default=False,
        ),
    ]
