# Generated by Django 3.2.2 on 2021-08-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0095_auto_20210815_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exel.materials'),
        ),
    ]
