# Generated by Django 3.2.2 on 2021-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0097_feed_feedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.CharField(max_length=60),
        ),
    ]
