# Generated by Django 3.2.2 on 2021-08-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0098_alter_feed_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user',
            new_name='username',
        ),
    ]
