# Generated by Django 3.2.4 on 2021-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0104_auto_20210827_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='duploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
