# Generated by Django 3.2.4 on 2021-10-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0109_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
