# Generated by Django 4.0.3 on 2022-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0114_brief_ca_alter_brief_kpi_alter_brief_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('sell', models.CharField(max_length=100, null=True)),
                ('buying_preority', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bying',
        ),
        migrations.DeleteModel(
            name='Dmp_priority',
        ),
    ]
