# Generated by Django 4.0.3 on 2022-08-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0115_buying_delete_bying_delete_dmp_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buying',
            new_name='BuyingDB',
        ),
    ]
