# Generated by Django 4.0.3 on 2022-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0116_rename_buying_buyingdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyingdb',
            old_name='buying_preority',
            new_name='buying_priority',
        ),
    ]
