# Generated by Django 4.0.3 on 2022-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0118_reportfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
