# Generated by Django 4.0.3 on 2022-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0119_rename_user_id_reportfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='user',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
