# Generated by Django 4.0.3 on 2022-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0120_remove_reportfile_user_reportfile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='username',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
