# Generated by Django 4.0.3 on 2022-08-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0121_reportfile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='age',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='competitors',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='duration1',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='duration2',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='duration3',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='income',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='rek',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='who_prep_materials',
        ),
        migrations.AddField(
            model_name='brief',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
