# Generated by Django 4.0.3 on 2022-08-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0122_remove_brief_age_remove_brief_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_file',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
