# Generated by Django 4.0.3 on 2022-08-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0123_all_file_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_file',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='all_file',
            name='dmp',
        ),
    ]
