# Generated by Django 3.2.2 on 2021-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0011_auto_20210529_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileexel',
            name='cover',
            field=models.FileField(upload_to='media/'),
        ),
    ]
