# Generated by Django 3.2.4 on 2021-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0014_auto_20210627_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('GB', 'GB'), ('DK', 'DK'), ('WO', 'WorkOrder')], default='gb', max_length=20)),
                ('file', models.FileField(upload_to='excel')),
                ('corrected', models.BooleanField(default=False)),
                ('file_content', models.BooleanField(default=False)),
            ],
        ),
    ]
