# Generated by Django 3.2.4 on 2021-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0018_alter_client_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
