# Generated by Django 3.2.4 on 2021-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0019_alter_client_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client',
            field=models.CharField(max_length=50),
        ),
    ]
