# Generated by Django 3.2.4 on 2021-07-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0021_client_name_rk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brief',
            old_name='KPI',
            new_name='age',
        ),
        migrations.AddField(
            model_name='brief',
            name='budget',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='client',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='income',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='interes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='materils',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='name_rk',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='period',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='plan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='posad',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='product',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='region',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='rek',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brief',
            name='type_act',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
