# Generated by Django 3.2.4 on 2021-07-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0025_alter_brief_posad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='sum_all',
        ),
    ]
