# Generated by Django 3.2.4 on 2021-07-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0057_auto_20210718_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='terms',
        ),
    ]
