# Generated by Django 3.2.4 on 2021-07-21 04:48

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0059_brief_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_file_cl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('client', models.CharField(max_length=50)),
                ('name_rk', models.CharField(max_length=100)),
                ('dmp', models.FileField(upload_to=exel.models.content_file_name)),
                ('brief', models.FileField(upload_to=exel.models.content_file_name)),
                ('report', models.FileField(upload_to=exel.models.content_file_name)),
            ],
        ),
    ]
