# Generated by Django 3.2.4 on 2021-07-21 05:12

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0060_all_file_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_file_cl',
            name='brief',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='all_file_cl',
            name='client',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_file_cl',
            name='dmp',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='all_file_cl',
            name='name_rk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='all_file_cl',
            name='report',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='all_file_cl',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
