# Generated by Django 3.2.4 on 2021-07-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0062_alter_all_file_cl_dmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_file_cl',
            name='dmp',
            field=models.FileField(upload_to='!!!'),
        ),
    ]
