# Generated by Django 3.2.4 on 2021-07-21 14:37

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0063_alter_all_file_cl_dmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_file_cl',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='CRM',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='UTP',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='companies_before',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='landing_page',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='official_list',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='client',
            name='file',
        ),
        migrations.AddField(
            model_name='client',
            name='brief',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AddField(
            model_name='client',
            name='calculation',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AddField(
            model_name='client',
            name='dmp',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
        migrations.AddField(
            model_name='client',
            name='report',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
    ]
