# Generated by Django 3.2.4 on 2021-07-22 07:30

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0066_auto_20210722_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='img',
            field=models.FileField(upload_to=exel.models.content),
        ),
    ]
