# Generated by Django 3.2.4 on 2021-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0080_all_file_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
