# Generated by Django 3.2.4 on 2021-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0082_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_file',
            name='name_rk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brief',
            name='name_rk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cleared',
            name='name_rk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_rk',
            field=models.CharField(max_length=200),
        ),
    ]
