# Generated by Django 3.2.4 on 2021-08-05 10:39

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0086_auto_20210804_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleared',
            name='access',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cleared',
            name='landing',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cleared',
            name='utm',
            field=models.FileField(null=True, upload_to=exel.models.content_file_name),
        ),
    ]
