# Generated by Django 3.2.4 on 2021-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0088_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='budget',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complete',
            name='period_c',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complete',
            name='period_p',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brief',
            name='KPI',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='brief',
            name='budget',
            field=models.CharField(max_length=30),
        ),
    ]
