# Generated by Django 3.2.2 on 2021-08-14 12:58

from django.db import migrations, models
import django.db.models.deletion
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0089_auto_20210805_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('client', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=exel.models.materials)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exel.data')),
            ],
        ),
    ]
