# Generated by Django 3.2.2 on 2021-08-14 13:59

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0091_auto_20210814_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='client',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name_rk',
        ),
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='file',
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(default=1, upload_to=exel.models.materials),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='name_rk',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
