# Generated by Django 3.2.2 on 2021-08-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0094_auto_20210815_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='client',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='username',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
