# Generated by Django 3.2.2 on 2021-08-16 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0102_auto_20210816_0757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
