# Generated by Django 3.2.4 on 2021-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0105_brief_duploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.CharField(max_length=100, null=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('phact', models.CharField(max_length=100, null=True)),
                ('procent', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
