# Generated by Django 3.2.4 on 2021-10-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0110_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='agency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bying',
            name='agency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dmp',
            name='agency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_common',
            name='agency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
