# Generated by Django 3.2.4 on 2021-11-03 16:20

from django.db import migrations, models
import exel.models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0112_auto_20211030_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=60)),
                ('bying_username', models.CharField(max_length=60)),
                ('manager_username', models.CharField(max_length=60)),
                ('report_common', models.FileField(null=True, upload_to=exel.models.content_file)),
            ],
        ),
    ]
