# Generated by Django 3.2.10 on 2022-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exel', '0113_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='ca',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
